"""Test-only acceptance inputs for the production reviewed-template bank."""

PRODUCTION_TEMPLATE_ACCEPTANCE_CASES = {'verify_bfs_frontier_choice_v1': {'primary_concept_id': 'breadth_first_search',
                                   'additional_mastery_concept_ids': [],
                                   'multi_concept_rationale': None,
                                   'source_refs': [{'chunk_id': 'lec2_bfs_layer_order',
                                                    'source_file': 'ai_lec2_uninformed_search.pdf',
                                                    'page_start': 31,
                                                    'page_end': 34}],
                                   'correct_answer': 'A',
                                   'wrong_answer': 'C',
                                   'malformed_answer': []},
 'verify_bfs_equal_cost_condition_v1': {'primary_concept_id': 'breadth_first_search',
                                        'additional_mastery_concept_ids': ['completeness_optimality_complexity'],
                                        'multi_concept_rationale': '本题同时直接验证 BFS '
                                                                   '的等步代价边界，以及最优性成立的适用条件；第二个 '
                                                                   'concept 是明确 mastery target，不是 '
                                                                   'supporting topic。',
                                        'source_refs': [{'chunk_id': 'lec2_bfs_properties',
                                                         'source_file': 'ai_lec2_uninformed_search.pdf',
                                                         'page_start': 35,
                                                         'page_end': 35}],
                                        'correct_answer': 'equal_cost',
                                        'wrong_answer': 'nonnegative',
                                        'malformed_answer': []},
 'verify_ucs_min_g_choice_v1': {'primary_concept_id': 'uniform_cost_search',
                                'additional_mastery_concept_ids': [],
                                'multi_concept_rationale': None,
                                'source_refs': [{'chunk_id': 'lec2_ucs_lowest_cost',
                                                 'source_file': 'ai_lec2_uninformed_search.pdf',
                                                 'page_start': 60,
                                                 'page_end': 62}],
                                'correct_answer': 'A',
                                'wrong_answer': 'B',
                                'malformed_answer': []},
 'verify_search_problem_components_v1': {'primary_concept_id': 'search_problem_formulation',
                                         'additional_mastery_concept_ids': [],
                                         'multi_concept_rationale': None,
                                         'source_refs': [{'chunk_id': 'lec2_search_problem_components',
                                                          'source_file': 'ai_lec2_uninformed_search.pdf',
                                                          'page_start': 6,
                                                          'page_end': 10}],
                                         'correct_answer': ['initial_state',
                                                            'actions',
                                                            'transition_model',
                                                            'goal_test',
                                                            'path_cost'],
                                         'wrong_answer': ['initial_state',
                                                          'actions',
                                                          'transition_model',
                                                          'goal_test'],
                                         'additional_wrong_answers': [['initial_state',
                                                                       'actions',
                                                                       'transition_model',
                                                                       'goal_test',
                                                                       'path_cost',
                                                                       'algorithm_choice'],
                                                                      ['initial_state',
                                                                       'actions',
                                                                       'transition_model',
                                                                       'goal_test',
                                                                       'path_cost',
                                                                       'frontier_container']],
                                         'malformed_answer': 'initial_state'},
 'verify_successor_operator_v1': {'primary_concept_id': 'state_space_and_operators',
                                  'additional_mastery_concept_ids': [],
                                  'multi_concept_rationale': None,
                                  'source_refs': [{'chunk_id': 'lec2_eight_puzzle_formulation',
                                                   'source_file': 'ai_lec2_uninformed_search.pdf',
                                                   'page_start': 12,
                                                   'page_end': 12}],
                                  'correct_answer': 'move_right',
                                  'wrong_answer': 'no_change',
                                  'malformed_answer': 'unknown_successor'},
 'verify_frontier_explored_membership_v1': {'primary_concept_id': 'frontier_and_explored_set',
                                            'additional_mastery_concept_ids': [],
                                            'multi_concept_rationale': None,
                                            'source_refs': [{'chunk_id': 'lec2_frontier_expansion',
                                                             'source_file': 'ai_lec2_uninformed_search.pdf',
                                                             'page_start': 20,
                                                             'page_end': 20},
                                                            {'chunk_id': 'lec2_graph_search_repeated_states',
                                                             'source_file': 'ai_lec2_uninformed_search.pdf',
                                                             'page_start': 27,
                                                             'page_end': 27}],
                                            'correct_answer': ['x_frontier', 'y_explored'],
                                            'wrong_answer': ['x_frontier'],
                                            'additional_wrong_answers': [['x_frontier',
                                                                          'y_explored',
                                                                          'x_explored'],
                                                                         ['x_frontier',
                                                                          'y_explored',
                                                                          'y_frontier']],
                                            'malformed_answer': ['x_frontier', 'x_frontier']},
 'verify_graph_search_repeated_state_handling_v1': {'primary_concept_id': 'tree_search_vs_graph_search',
                                                    'additional_mastery_concept_ids': [],
                                                    'multi_concept_rationale': None,
                                                    'source_refs': [{'chunk_id': 'lec2_graph_search_repeated_states',
                                                                     'source_file': 'ai_lec2_uninformed_search.pdf',
                                                                     'page_start': 27,
                                                                     'page_end': 27}],
                                                    'correct_answer': 'discard_repeat',
                                                    'wrong_answer': 'expand_then_record',
                                                    'malformed_answer': ['discard_repeat']},
 'verify_dfs_frontier_choice_v1': {'primary_concept_id': 'depth_first_search',
                                   'additional_mastery_concept_ids': [],
                                   'multi_concept_rationale': None,
                                   'source_refs': [{'chunk_id': 'lec2_dfs_deepest_first',
                                                    'source_file': 'ai_lec2_uninformed_search.pdf',
                                                    'page_start': 37,
                                                    'page_end': 46},
                                                   {'chunk_id': 'support_stack_lifo',
                                                    'source_file': 'ds_stack_queue_priority_queue.pdf',
                                                    'page_start': 1,
                                                    'page_end': 2}],
                                   'correct_answer': 'node_c',
                                   'wrong_answer': 'node_b',
                                   'malformed_answer': 'unknown_node'},
 'verify_iddfs_depth_limit_schedule_v1': {'primary_concept_id': 'iterative_deepening_search',
                                          'additional_mastery_concept_ids': [],
                                          'multi_concept_rationale': None,
                                          'source_refs': [{'chunk_id': 'lec2_iddfs_strategy',
                                                           'source_file': 'ai_lec2_uninformed_search.pdf',
                                                           'page_start': 53,
                                                           'page_end': 57}],
                                          'correct_answer': 'restart_limit_2',
                                          'wrong_answer': 'continue_limit_2',
                                          'malformed_answer': 'unknown_limit_action'},
 'verify_informed_search_g_h_roles_v1': {'primary_concept_id': 'informed_search_and_heuristics',
                                         'additional_mastery_concept_ids': [],
                                         'multi_concept_rationale': None,
                                         'question_type': 'multiple_choice',
                                         'deterministic_scorer': 'multiple_choice_v1',
                                         'evidence_strength': 'direct',
                                         'source_refs': [{'chunk_id': 'lec3_a_star_f_g_h',
                                                          'source_file': 'ai_lec3_informed_search.pdf',
                                                          'page_start': 18,
                                                          'page_end': 18}],
                                         'correct_answer': ['g_path_cost', 'h_goal_estimate'],
                                         'wrong_answer': ['g_path_cost'],
                                         'additional_wrong_answers': [['g_path_cost',
                                                                       'h_goal_estimate',
                                                                       'h_paid_cost'],
                                                                      ['h_paid_cost',
                                                                       'g_goal_estimate']],
                                         'malformed_answer': 'g_path_cost'},
 'verify_greedy_min_h_choice_v1': {'primary_concept_id': 'greedy_best_first_search',
                                   'additional_mastery_concept_ids': [],
                                   'multi_concept_rationale': None,
                                   'question_type': 'single_choice',
                                   'deterministic_scorer': 'single_choice_v1',
                                   'evidence_strength': 'direct',
                                   'source_refs': [{'chunk_id': 'lec3_greedy_search',
                                                    'source_file': 'ai_lec3_informed_search.pdf',
                                                    'page_start': 9,
                                                    'page_end': 9}],
                                   'correct_answer': 'node_b',
                                   'wrong_answer': 'node_d',
                                   'malformed_answer': 'unknown_node'},
 'verify_astar_min_f_choice_v1': {'primary_concept_id': 'a_star_search',
                                  'additional_mastery_concept_ids': [],
                                  'multi_concept_rationale': None,
                                  'question_type': 'single_choice',
                                  'deterministic_scorer': 'single_choice_v1',
                                  'evidence_strength': 'direct',
                                  'source_refs': [{'chunk_id': 'lec3_a_star_f_g_h',
                                                   'source_file': 'ai_lec3_informed_search.pdf',
                                                   'page_start': 18,
                                                   'page_end': 18},
                                                  {'chunk_id': 'lec3_a_star_f_g_h',
                                                   'source_file': 'ai_lec3_informed_search.pdf',
                                                   'page_start': 21,
                                                   'page_end': 21}],
                                  'correct_answer': 'node_c',
                                  'wrong_answer': 'node_d',
                                  'additional_wrong_answers': ['node_a', 'node_b'],
                                  'malformed_answer': 'unknown_node'},
 'verify_admissibility_no_overestimate_v1': {'primary_concept_id': 'admissibility_and_consistency',
                                             'additional_mastery_concept_ids': [],
                                             'multi_concept_rationale': None,
                                             'question_type': 'single_choice',
                                             'deterministic_scorer': 'single_choice_v1',
                                             'evidence_strength': 'direct',
                                             'source_refs': [{'chunk_id': 'lec3_admissibility',
                                                              'source_file': 'ai_lec3_informed_search.pdf',
                                                              'page_start': 30,
                                                              'page_end': 30}],
                                             'correct_answer': 'equal_and_under',
                                             'wrong_answer': 'p_overestimates',
                                             'malformed_answer': 'unknown_heuristic_table'},
 'verify_path_cost_accumulation_v1': {'primary_concept_id': 'search_problem_formulation',
                                      'verification_goal': '在题面明确每步单位代价时，把解中三个行动的代价累计为路径代价。',
                                      'capability_boundary': '只验证三个单位行动的基础累计；不验证非单位代价、UCS、启发式或完整问题建模。',
                                      'evidence_strength': 'supported_inference',
                                      'source_review_note': 'Lec2 p.11 将解定义为行动序列，p.12 明确八数码每一步代价为 '
                                                            '1。三次已声明单位代价行动得到 3 '
                                                            '是封闭算术推断；课件没有在此页给出一般非单位步代价的求和公式。',
                                      'source_refs': [{'chunk_id': 'lec2_solution_and_optimality',
                                                       'source_file': 'ai_lec2_uninformed_search.pdf',
                                                       'page_start': 11,
                                                       'page_end': 11},
                                                      {'chunk_id': 'lec2_eight_puzzle_formulation',
                                                       'source_file': 'ai_lec2_uninformed_search.pdf',
                                                       'page_start': 12,
                                                       'page_end': 12}],
                                      'question_type': 'single_choice',
                                      'deterministic_scorer': 'single_choice_v1',
                                      'expected_answer_position': 3,
                                      'correct_answer': 'three_action_costs',
                                      'wrong_answer': 'four_nodes',
                                      'malformed_answer': ['three_action_costs'],
                                      'additional_mastery_concept_ids': [],
                                      'multi_concept_rationale': None},
 'verify_search_node_state_distinction_v1': {'primary_concept_id': 'tree_search_vs_graph_search',
                                             'verification_goal': '区分从 frontier 取出的 search node 与由 '
                                                                  'STATE[node] 表示并记录到 closed 的 '
                                                                  'problem state。',
                                             'capability_boundary': '只验证 node 与 state 的表示关系；不规定完整 '
                                                                    'node schema，不覆盖 duplicate '
                                                                    'replacement 或 reopening。',
                                             'evidence_strength': 'supported_inference',
                                             'source_review_note': 'Lec2 p.27 的 graph-search '
                                                                   '伪代码直接区分从 frontier 取出的 '
                                                                   'node、STATE[node] 与 closed 中记录的 '
                                                                   'state，并以 STATE[node] 检查 '
                                                                   'closed。不同 search node 可以表示同一 '
                                                                   'problem state 是由这一结构和重复 state '
                                                                   '处理支持的推论，不是课件逐字给出的 node 定义。',
                                             'source_refs': [{'chunk_id': 'lec2_graph_search_repeated_states',
                                                              'source_file': 'ai_lec2_uninformed_search.pdf',
                                                              'page_start': 27,
                                                              'page_end': 27}],
                                             'question_type': 'single_choice',
                                             'deterministic_scorer': 'single_choice_v1',
                                             'expected_answer_position': 1,
                                             'correct_answer': 'different_nodes_same_state',
                                             'wrong_answer': 'same_state_means_same_node',
                                             'malformed_answer': ['different_nodes_same_state'],
                                             'additional_mastery_concept_ids': [],
                                             'multi_concept_rationale': None},
 'verify_dfs_infinite_branch_risk_v1': {'primary_concept_id': 'depth_first_search',
                                        'verification_goal': '在题面明确存在先行无限分支时，识别 deepest-first DFS '
                                                             '不保证找到另一条浅层目标分支。',
                                        'capability_boundary': '只验证受限 infinite-branch '
                                                               '场景中的完备性风险；不测时间、空间或所有有限问题上的表现。',
                                        'evidence_strength': 'supported_inference',
                                        'source_review_note': 'Lec2 pp.37–46 直接支持 DFS 扩展最深 '
                                                              'frontier 节点，p.48 直接将 DFS '
                                                              '标为非完备、非最优。题面补充一个无限延伸且无目标的分支，把这两项课件事实用于一个封闭场景；课件该页未单独给出无限分支的文字证明。',
                                        'source_refs': [{'chunk_id': 'lec2_dfs_deepest_first',
                                                         'source_file': 'ai_lec2_uninformed_search.pdf',
                                                         'page_start': 37,
                                                         'page_end': 46},
                                                        {'chunk_id': 'lec2_dfs_properties',
                                                         'source_file': 'ai_lec2_uninformed_search.pdf',
                                                         'page_start': 48,
                                                         'page_end': 48}],
                                        'question_type': 'single_choice',
                                        'deterministic_scorer': 'single_choice_v1',
                                        'expected_answer_position': 2,
                                        'correct_answer': 'may_not_find_shallow_goal',
                                        'wrong_answer': 'must_find_shallow_goal',
                                        'malformed_answer': ['may_not_find_shallow_goal'],
                                        'additional_mastery_concept_ids': [],
                                        'multi_concept_rationale': None},
 'verify_search_algorithm_properties_v1': {'primary_concept_id': 'completeness_optimality_complexity',
                                           'verification_goal': '识别 IDDFS 的完备性，以及在所有行动代价相同时的最优性条件。',
                                           'capability_boundary': '只验证 IDDFS 的一个条件性性质陈述；不构成 '
                                                                  'BFS、DFS、IDDFS、UCS 的完整性质矩阵。',
                                           'evidence_strength': 'supported_inference',
                                           'source_review_note': 'Lec2 p.53 '
                                                                 '建立“迭代加深的深度优先搜索”段落主题，p.53–57 '
                                                                 '连续描述迭代加深，紧随其后的 p.58 '
                                                                 '给出完备性与“所有行动代价相同”时最优的性能结论。因此 '
                                                                 'IDDFS 正确项由这一多页上下文链支持；BFS、DFS、UCS '
                                                                 '页面只用于排除其余选项。',
                                           'source_refs': [{'chunk_id': 'lec2_iddfs_strategy',
                                                            'source_file': 'ai_lec2_uninformed_search.pdf',
                                                            'page_start': 53,
                                                            'page_end': 53,
                                                            'context_only': True},
                                                           {'chunk_id': 'lec2_iddfs_properties',
                                                            'source_file': 'ai_lec2_uninformed_search.pdf',
                                                            'page_start': 58,
                                                            'page_end': 58,
                                                            'primary_evidence': True},
                                                           {'chunk_id': 'lec2_bfs_properties',
                                                            'source_file': 'ai_lec2_uninformed_search.pdf',
                                                            'page_start': 35,
                                                            'page_end': 35},
                                                           {'chunk_id': 'lec2_dfs_properties',
                                                            'source_file': 'ai_lec2_uninformed_search.pdf',
                                                            'page_start': 48,
                                                            'page_end': 48},
                                                           {'chunk_id': 'lec2_ucs_properties',
                                                            'source_file': 'ai_lec2_uninformed_search.pdf',
                                                            'page_start': 63,
                                                            'page_end': 63}],
                                           'question_type': 'single_choice',
                                           'deterministic_scorer': 'single_choice_v1',
                                           'expected_answer_position': 4,
                                           'correct_answer': 'iddfs_equal_cost_optimal',
                                           'wrong_answer': 'dfs_complete_not_optimal',
                                           'malformed_answer': ['iddfs_equal_cost_optimal'],
                                           'additional_mastery_concept_ids': [],
                                           'multi_concept_rationale': None},
 'verify_greedy_suboptimality_v1': {'primary_concept_id': 'greedy_best_first_search',
                                    'verification_goal': '识别贪婪搜索可能非最优，并将该限制与启发式依赖联系起来。',
                                    'capability_boundary': '只验证可能非最优的性质边界；不构造反例，不推断 Greedy '
                                                           '总失败或完整性。',
                                    'evidence_strength': 'direct',
                                    'source_review_note': 'Lec3 p.14 的 bad case '
                                                          '直接列出“非完备、非最优、依赖启发式函数”。本题只复现“可能非最优”的限制，不以个例推广为总会失败。',
                                    'source_refs': [{'chunk_id': 'lec3_greedy_limitations',
                                                     'source_file': 'ai_lec3_informed_search.pdf',
                                                     'page_start': 14,
                                                     'page_end': 14}],
                                    'question_type': 'single_choice',
                                    'deterministic_scorer': 'single_choice_v1',
                                    'expected_answer_position': 1,
                                    'correct_answer': 'may_be_nonoptimal',
                                    'wrong_answer': 'always_optimal',
                                    'malformed_answer': ['may_be_nonoptimal'],
                                    'additional_mastery_concept_ids': [],
                                    'multi_concept_rationale': None},
 'verify_astar_f_value_v1': {'primary_concept_id': 'a_star_search',
                             'verification_goal': '根据 f(n)=g(n)+h(n) 对单个节点进行一次 f 值计算，而不是比较多个 '
                                                  'frontier 节点。',
                             'capability_boundary': '只验证一次公式代入；不测 min-f selection、可采纳性、一致性或 A* '
                                                    '最优性。',
                             'evidence_strength': 'direct',
                             'source_review_note': 'Lec3 p.18 直接定义 f(n)=g(n)+h(n) 以及 g/h 的含义。与现有 '
                                                   'min-f '
                                                   '模板不同，本题不要求在多个节点间选择；仍需负责人判断这条细粒度计算能力是否值得作为独立 '
                                                   'evidence slice。',
                             'source_refs': [{'chunk_id': 'lec3_a_star_f_g_h',
                                              'source_file': 'ai_lec3_informed_search.pdf',
                                              'page_start': 18,
                                              'page_end': 18}],
                             'question_type': 'single_choice',
                             'deterministic_scorer': 'single_choice_v1',
                             'expected_answer_position': 2,
                             'correct_answer': 'g_plus_h',
                             'wrong_answer': 'h_only',
                             'malformed_answer': ['g_plus_h'],
                             'additional_mastery_concept_ids': [],
                             'multi_concept_rationale': None},
 'verify_consistency_edge_check_v1': {'primary_concept_id': 'admissibility_and_consistency',
                                      'verification_goal': '对一条明确边代入一致性不等式，并识别等号允许而不据此推广为全局一致性。',
                                      'capability_boundary': '只验证单条边的一致性条件；不证明整个 heuristic '
                                                             '对所有边一致，也不证明 A* 的完整最优性条件。',
                                      'evidence_strength': 'direct',
                                      'source_review_note': 'Lec3 p.39 直接给出对每个节点和任一行动后继的 '
                                                            "h(n)≤cost(n,a,n')+h(n')，并指出一致性可推出可采纳性。题面只检查一条边，明确不把它说成全局证明。",
                                      'source_refs': [{'chunk_id': 'lec3_consistency',
                                                       'source_file': 'ai_lec3_informed_search.pdf',
                                                       'page_start': 39,
                                                       'page_end': 39}],
                                      'question_type': 'single_choice',
                                      'deterministic_scorer': 'single_choice_v1',
                                      'expected_answer_position': 3,
                                      'correct_answer': 'edge_satisfies_equality',
                                      'wrong_answer': 'proves_global_consistency',
                                      'malformed_answer': ['edge_satisfies_equality'],
                                      'additional_mastery_concept_ids': [],
                                      'multi_concept_rationale': None},

 'verify_local_search_final_state_focus_v1': {
     'primary_concept_id': 'local_search',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别 Lec4 局部搜索总体 framing 中对候选状态或解的质量评价，而不是维护完整搜索路径。',
     'capability_boundary': '只验证本课程中 local search 的 state/candidate-solution focus 与 path/frontier/exhaustive search 的区别；不声称所有局部或种群方法只维护一个状态，不验证 Hill Climbing、Simulated Annealing、Evolutionary Search、全局最优性、收敛性、完整路径重建或所有 local-search 变体。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec4 p.11 直接说明很多问题只关心最终返回状态是否达到目标，而不关心完整路径；同页补充当前状态邻域中的近邻解会被评价。pp.9–10 提供局部搜索主题上下文。本题只测试 state/candidate-solution focus。',
     'source_refs': [{'chunk_id': 'lec4_local_search_state_neighbors', 'source_file': 'ai_lec4_local_search_and_llm_search.pdf', 'page_start': 9, 'page_end': 11}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 2,
     'correct_answer': 'candidate_solution_quality',
     'wrong_answer': 'complete_action_sequence',
     'malformed_answer': 'unknown_local_search_choice',
 },
 'verify_hill_climbing_stop_at_local_best_v1': {
     'primary_concept_id': 'hill_climbing',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别基本爬山法在没有更好邻居时停止。',
     'capability_boundary': '只验证基本停止条件；不证明停止状态是全局最优，也不覆盖随机重启等变体。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec4 p.12 直接列出基本爬山法循环：移动到邻域内最好的解；如果没有更好的解，则停止搜索。',
     'source_refs': [{'chunk_id': 'lec4_hill_climbing', 'source_file': 'ai_lec4_local_search_and_llm_search.pdf', 'page_start': 12, 'page_end': 16}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 3,
     'correct_answer': 'stop_search',
     'wrong_answer': 'always_restart',
     'malformed_answer': 'unknown_hill_choice',
 },
 'verify_simulated_annealing_worse_successor_v1': {
     'primary_concept_id': 'simulated_annealing',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别模拟退火对较差后继按概率接受且随机性随温度降低而减弱。',
     'capability_boundary': '只验证接受规则的定性描述；不要求计算温度函数或接受概率。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec4 p.19 直接说明更优后继直接跳转、较差后继按概率决定是否跳转，并说明温度随时间变化、后期随机性减弱。',
     'source_refs': [{'chunk_id': 'lec4_simulated_annealing', 'source_file': 'ai_lec4_local_search_and_llm_search.pdf', 'page_start': 17, 'page_end': 19}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 4,
     'correct_answer': 'probabilistic_accept',
     'wrong_answer': 'always_reject',
     'malformed_answer': 'unknown_annealing_choice',
 },
 'verify_evolutionary_search_parent_cycle_v1': {
     'primary_concept_id': 'evolutionary_search',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别 Lec4 pp.20–25 课件示例中“选择亲本→杂交→随机突变→形成下一代”的阶段顺序。',
     'capability_boundary': '只验证 Lec4 所示这一演化算法示例的阶段顺序；不推广到所有演化算法变体，也不证明收敛、最优性或具体应用效果。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec4 pp.20–25 直接展示本课程示例按适应度选择亲本、进行杂交、施加随机突变并形成下一代的循环；题干已明确限定为该课件示例。',
     'source_refs': [{'chunk_id': 'lec4_evolutionary_search_cycle', 'source_file': 'ai_lec4_local_search_and_llm_search.pdf', 'page_start': 20, 'page_end': 25}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 1,
     'correct_answer': 'fitness_parent_cycle',
     'wrong_answer': 'mutation_before_crossover',
     'malformed_answer': 'unknown_evolutionary_choice',
 },
 'verify_minimax_max_min_value_choice_v1': {
     'primary_concept_id': 'minimax_search',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '在封闭的 MAX 节点数值实例中选择较大的 minimax 后继值。',
     'capability_boundary': '只验证一个给定 minimax 值的 MAX 选择；不证明完整博弈树搜索、深度截断或策略最优性。',
     'evidence_strength': 'direct_plus_closed_instance',
     'source_review_note': 'Lec5 pp.16–19 直接给出 MAX 节点取后继 minimax 值的最大值、MIN 节点取最小值；题面只提供 3 和 5 的封闭实例。',
     'source_refs': [{'chunk_id': 'lec5_minimax_search', 'source_file': 'ai_lec5_adversarial_search.pdf', 'page_start': 16, 'page_end': 19}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 2,
     'correct_answer': 'value_5',
     'wrong_answer': 'value_3',
     'malformed_answer': 'unknown_minimax_choice',
 },
 'verify_alpha_beta_prune_when_bounds_cross_v1': {
     'primary_concept_id': 'alpha_beta_pruning',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '在题面给出 alpha>beta 的封闭状态下识别剪去未访问后继。',
     'capability_boundary': '只验证课件明确的 alpha>beta 剪枝条件；不验证节点排序、剪枝数量或完整 minimax 策略。',
     'evidence_strength': 'direct_plus_closed_instance',
     'source_review_note': 'Lec5 p.30 直接说明当 alpha>beta 时未访问后继可被剪枝，p.31 给出对应递归伪代码；题面实例固定 alpha=5、beta=4。',
     'source_refs': [{'chunk_id': 'lec5_alpha_beta_pruning', 'source_file': 'ai_lec5_adversarial_search.pdf', 'page_start': 20, 'page_end': 31}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 3,
     'correct_answer': 'prune_remaining',
     'wrong_answer': 'visit_all',
     'malformed_answer': 'unknown_alpha_beta_choice',
 },
 'verify_mcts_four_stage_order_v1': {
     'primary_concept_id': 'monte_carlo_tree_search',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别 MCTS 的选择、扩展、模拟、回溯四阶段顺序。',
     'capability_boundary': '只验证课件列出的四阶段顺序；不证明 UCB 数值、模拟策略或对抗视角下的统计细节。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec6 p.20 直接列出 MCTS 四阶段及其顺序：selection、expansion、simulation、backpropagation。',
     'source_refs': [{'chunk_id': 'lec6_mcts_four_stages', 'source_file': 'ai_lec6_mcts_and_search_summary.pdf', 'page_start': 20, 'page_end': 20}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 2,
     'correct_answer': 'select_expand_simulate_backprop',
     'wrong_answer': 'expand_simulate_select_backprop',
     'malformed_answer': 'unknown_mcts_choice',
 },
 'verify_ucb_upper_bound_selection_v1': {
     'primary_concept_id': 'upper_confidence_bound',
     'additional_mastery_concept_ids': [],
     'multi_concept_rationale': None,
     'verification_goal': '识别 UCB 选择估计上限最高动作的规则。',
     'capability_boundary': '只验证 UCB 的定性选择规则；不要求计算探索项，也不等同于完整掌握探索—利用策略。',
     'evidence_strength': 'direct',
     'source_review_note': 'Lec6 p.19 直接将 UCB 写为 Q_k+δ(k)，并说明优先采用估计范围上限较高的动作；探索项随访问次数变化。',
     'source_refs': [{'chunk_id': 'lec6_upper_confidence_bound', 'source_file': 'ai_lec6_mcts_and_search_summary.pdf', 'page_start': 19, 'page_end': 19}],
     'question_type': 'single_choice',
     'deterministic_scorer': 'single_choice_v1',
     'expected_answer_position': 1,
     'correct_answer': 'highest_upper_bound',
     'wrong_answer': 'highest_mean_only',
     'malformed_answer': 'unknown_ucb_choice',
 },
}


PRODUCTION_SINGLE_CHOICE_DISPLAY_CONTRACTS = {'verify_bfs_frontier_choice_v1': {'choice_ids': ['A', 'B', 'C'], 'expected_choice_id': 'A'},
 'verify_bfs_equal_cost_condition_v1': {'choice_ids': ['equal_cost',
                                                       'nonnegative',
                                                       'acyclic',
                                                       'priority_queue'],
                                        'expected_choice_id': 'equal_cost'},
 'verify_ucs_min_g_choice_v1': {'choice_ids': ['B', 'A', 'C'], 'expected_choice_id': 'A'},
 'verify_successor_operator_v1': {'choice_ids': ['swap_non_adjacent',
                                                 'move_right',
                                                 'move_to_bottom_right',
                                                 'no_change'],
                                  'expected_choice_id': 'move_right'},
 'verify_graph_search_repeated_state_handling_v1': {'choice_ids': ['expand_then_record',
                                                                   'remove_and_expand',
                                                                   'discard_repeat',
                                                                   'keep_until_empty'],
                                                    'expected_choice_id': 'discard_repeat'},
 'verify_dfs_frontier_choice_v1': {'choice_ids': ['node_a', 'node_b', 'nodes_b_and_c', 'node_c'],
                                   'expected_choice_id': 'node_c'},
 'verify_iddfs_depth_limit_schedule_v1': {'choice_ids': ['restart_limit_2',
                                                         'continue_limit_2',
                                                         'restart_limit_1',
                                                         'run_unlimited_dfs'],
                                          'expected_choice_id': 'restart_limit_2'},
 'verify_greedy_min_h_choice_v1': {'choice_ids': ['node_a', 'node_b', 'node_c', 'node_d'],
                                   'expected_choice_id': 'node_b'},
 'verify_astar_min_f_choice_v1': {'choice_ids': ['node_a', 'node_b', 'node_c', 'node_d'],
                                  'expected_choice_id': 'node_c'},
 'verify_admissibility_no_overestimate_v1': {'choice_ids': ['p_overestimates',
                                                            'q_overestimates',
                                                            'both_overestimate',
                                                            'equal_and_under'],
                                             'expected_choice_id': 'equal_and_under'},
 'verify_path_cost_accumulation_v1': {'choice_ids': ['last_step_only',
                                                     'two_actions',
                                                     'three_action_costs',
                                                     'four_nodes'],
                                      'expected_choice_id': 'three_action_costs'},
 'verify_search_node_state_distinction_v1': {'choice_ids': ['different_nodes_same_state',
                                                            'same_state_means_same_node',
                                                            'state_contains_closed',
                                                            'must_expand_both'],
                                             'expected_choice_id': 'different_nodes_same_state'},
 'verify_dfs_infinite_branch_risk_v1': {'choice_ids': ['must_find_shallow_goal',
                                                       'may_not_find_shallow_goal',
                                                       'switches_to_bfs',
                                                       'must_be_optimal'],
                                        'expected_choice_id': 'may_not_find_shallow_goal'},
 'verify_search_algorithm_properties_v1': {'choice_ids': ['bfs_equal_cost_for_complete',
                                                          'dfs_complete_not_optimal',
                                                          'ucs_not_optimal',
                                                          'iddfs_equal_cost_optimal'],
                                           'expected_choice_id': 'iddfs_equal_cost_optimal'},
 'verify_greedy_suboptimality_v1': {'choice_ids': ['may_be_nonoptimal',
                                                   'always_optimal',
                                                   'h_is_paid_cost',
                                                   'uses_g_plus_h'],
                                    'expected_choice_id': 'may_be_nonoptimal'},
 'verify_astar_f_value_v1': {'choice_ids': ['g_only', 'g_plus_h', 'h_only', 'g_minus_h'],
                             'expected_choice_id': 'g_plus_h'},
 'verify_consistency_edge_check_v1': {'choice_ids': ['strictly_less_required',
                                                     'admissibility_comparison',
                                                     'edge_satisfies_equality',
                                                     'proves_global_consistency'],
                                      'expected_choice_id': 'edge_satisfies_equality'},
 'verify_local_search_final_state_focus_v1': {'choice_ids': ['complete_action_sequence', 'candidate_solution_quality', 'frontier_systematic', 'state_space_exhaustive'],
                                              'expected_choice_id': 'candidate_solution_quality'},
 'verify_hill_climbing_stop_at_local_best_v1': {'choice_ids': ['move_worse', 'expand_all_paths', 'stop_search', 'always_restart'],
                                               'expected_choice_id': 'stop_search'},
 'verify_simulated_annealing_worse_successor_v1': {'choice_ids': ['always_reject', 'always_accept', 'only_best', 'probabilistic_accept'],
                                                  'expected_choice_id': 'probabilistic_accept'},
 'verify_evolutionary_search_parent_cycle_v1': {'choice_ids': ['fitness_parent_cycle', 'mutation_before_crossover', 'crossover_before_selection', 'mutation_before_selection'],
                                                'expected_choice_id': 'fitness_parent_cycle'},
 'verify_minimax_max_min_value_choice_v1': {'choice_ids': ['value_3', 'value_5', 'average_4', 'min_value'],
                                            'expected_choice_id': 'value_5'},
 'verify_alpha_beta_prune_when_bounds_cross_v1': {'choice_ids': ['visit_all', 'reset_bounds', 'prune_remaining', 'swap_bounds'],
                                                 'expected_choice_id': 'prune_remaining'},
 'verify_mcts_four_stage_order_v1': {'choice_ids': ['expand_simulate_select_backprop', 'select_expand_simulate_backprop', 'simulate_select_expand_backprop', 'select_simulate_backprop_expand'],
                                     'expected_choice_id': 'select_expand_simulate_backprop'},
 'verify_ucb_upper_bound_selection_v1': {'choice_ids': ['highest_upper_bound', 'highest_mean_only', 'lowest_upper_bound', 'least_visited_only'],
                                        'expected_choice_id': 'highest_upper_bound'}}


PRODUCTION_MULTIPLE_CHOICE_DISPLAY_CONTRACTS = {'verify_search_problem_components_v1': ['initial_state',
                                         'algorithm_choice',
                                         'actions',
                                         'transition_model',
                                         'frontier_container',
                                         'goal_test',
                                         'path_cost'],
 'verify_frontier_explored_membership_v1': ['x_frontier',
                                            'x_explored',
                                            'y_explored',
                                            'y_frontier',
                                            'z_frontier'],
 'verify_informed_search_g_h_roles_v1': ['g_path_cost',
                                         'h_paid_cost',
                                         'h_goal_estimate',
                                         'g_goal_estimate']}
